defaultBackend:
  type: filesystem
  path: "data/"

resourceBackends:
  User:
    type: filesystem
    path: "data/users"

namespacedResourceBackends:
  Project:
    type: sqlite
    connectionString: "data/projects.db"
